#!/bin/bash
cd /Users/harbertt11/_The\ University\ of\ Akron/FALL\ 2015/Compiler\ Design/HW1\ Calculator\ 1.0/bin 
cmake /Users/harbertt11/_The\ University\ of\ Akron/FALL\ 2015/Compiler\ Design/HW1\ Calculator\ 1.0
make